data:
  batch_size: 16
  num_workers: 4
  train_path: "./data/mixer_64/training.csv"
  val_path: "./data/mixer_64/validation.csv"
  test_path: "./data/mixer_64/testing.csv"
  coordinate_file_path: "./data/mixer_64/coordinates.csv"
  resolution: 64
  max_samples: 0